-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2011-07-24 18:34:02 PDT
--   site:      SQL Server 2005
--   type:      SQL Server 2005






CREATE TABLE Classification 
    (
     primary_classification VARCHAR (128) , 
     subclass1 VARCHAR (128) , 
     subclass2 VARCHAR (128) , 
     subclass3 VARCHAR (128) , 
     comments VARCHAR (512) , 
     classification_id UNIQUEIDENTIFIER NOT NULL , 
     subclass4 VARCHAR (128) , 
     CONSTRAINT Classification_PK PRIMARY KEY NONCLUSTERED (classification_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE ClinicalNote 
    (
     clinical_note_id UNIQUEIDENTIFIER NOT NULL , 
     note VARCHAR (512) NOT NULL , 
     patient_id UNIQUEIDENTIFIER NOT NULL , 
     soft_delete_flag BIT , 
     clinical_note_type_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT "ClinicalNote PK" PRIMARY KEY NONCLUSTERED (clinical_note_id, patient_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Clinical_Note_Audit 
    (
     audit_date DATETIME NOT NULL , 
     action_type VARCHAR (10) NOT NULL , 
     access_seq INTEGER NOT NULL , 
     user_account_id UNIQUEIDENTIFIER NOT NULL , 
     patient_id1 UNIQUEIDENTIFIER NOT NULL , 
     user_account VARCHAR (60) NOT NULL , 
     clinical_note_id UNIQUEIDENTIFIER NOT NULL , 
     patient_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT PK_Clinical_Note_Audit PRIMARY KEY NONCLUSTERED (access_seq, patient_id1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Clinical_Note_Type 
    (
     clinical_note_type_id UNIQUEIDENTIFIER NOT NULL , 
     cn_type VARCHAR (60) , 
     CONSTRAINT "Clinical_Note_Type PK" PRIMARY KEY NONCLUSTERED (clinical_note_type_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE "GenEntity-GenAnnot" 
    (
     Genomic_Entity_genomic_entity_id UNIQUEIDENTIFIER NOT NULL , 
     GenomicAnnotation_gap_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT Relation_23__IDX PRIMARY KEY NONCLUSTERED (Genomic_Entity_genomic_entity_id, GenomicAnnotation_gap_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Gene 
    (
     gene_id UNIQUEIDENTIFIER , 
     HUGO_gene_symbol VARCHAR (6) NOT NULL 
    )
    ON "default"
GO 

    



CREATE TABLE Gene_GenAnnot 
    (
     GenomicAnnotation_gap_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT Relation_24__IDX PRIMARY KEY NONCLUSTERED (GenomicAnnotation_gap_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE GenomicAnalysis 
    (
     analysis_id INTEGER NOT NULL , 
     analysis_date DATETIME NOT NULL , 
     coverage INTEGER , 
     analysis_type VARCHAR (120) , 
     analysis_comments VARCHAR (1024) , 
     biopsy_seq INTEGER NOT NULL , 
     patient_id1 UNIQUEIDENTIFIER NOT NULL , 
     patient_id UNIQUEIDENTIFIER NOT NULL , 
     classification_id UNIQUEIDENTIFIER , 
     CONSTRAINT "GenomicAnalysis PK" PRIMARY KEY NONCLUSTERED (analysis_id, biopsy_seq, patient_id1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE GenomicAnnotation 
    (
     gap_id UNIQUEIDENTIFIER NOT NULL , 
     chromosome_loc VARCHAR (8) NOT NULL , 
     chr_start_pos INTEGER , 
     chr_end_pos INTEGER , 
     cds_start_pos INTEGER , 
     cds_end_pos INTEGER , 
     UCSC_coordinates VARCHAR (30) , 
     gat_id UNIQUEIDENTIFIER NOT NULL , 
     annotation VARCHAR (2048) , 
     soft_delete_flag BIT , 
     annotation_date DATETIME NOT NULL , 
     bioportal_evidence_code VARCHAR (12) , 
     reference_id UNIQUEIDENTIFIER , 
     user_account_id UNIQUEIDENTIFIER NOT NULL , 
     user_account VARCHAR (60) NOT NULL , 
     CONSTRAINT "GenomicFeature PK" PRIMARY KEY NONCLUSTERED (gap_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE GenomicAnnotationType 
    (
     gat_id UNIQUEIDENTIFIER NOT NULL , 
     ga_type VARCHAR (128) NOT NULL , 
     CONSTRAINT "GenomicAnnotationType PK" PRIMARY KEY NONCLUSTERED (gat_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Genomic_Entity 
    (
     genomic_entity_id UNIQUEIDENTIFIER NOT NULL , 
     ge_description VARCHAR (128) , 
     get_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT "Genomic_Entity PK" PRIMARY KEY NONCLUSTERED (genomic_entity_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Genomic_Entity_Type 
    (
     get_id UNIQUEIDENTIFIER NOT NULL , 
     ge_type VARCHAR (80) NOT NULL , 
     CONSTRAINT "Genomic_Entity_Type PK" PRIMARY KEY NONCLUSTERED (get_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Patient 
    (
     patient_id UNIQUEIDENTIFIER NOT NULL , 
     sex VARCHAR (6) , 
     date_of_birth DATETIME , 
     date_of_death DATETIME , 
     family_history_flag BIT , 
     soft_delete_flag BIT , 
     CONSTRAINT "Patient PK" PRIMARY KEY NONCLUSTERED (patient_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Patient_Biopsy 
    (
     biopsy_seq INTEGER NOT NULL , 
     biopsy_date DATETIME , 
     diagnosis VARCHAR (60) , 
     histological_image IMAGE , 
     patient_id UNIQUEIDENTIFIER NOT NULL , 
     site_classification_id UNIQUEIDENTIFIER NOT NULL , 
     cancer_classification_id UNIQUEIDENTIFIER , 
     parent_biopsy_seq INTEGER , 
     parent_patient_id UNIQUEIDENTIFIER , 
     soft_delete_flag BIT , 
     CONSTRAINT Biopsy_PK PRIMARY KEY NONCLUSTERED (biopsy_seq, patient_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Relation_18 
    (
     StructuralVariation_structural_variation_id UNIQUEIDENTIFIER NOT NULL , 
     Genomic_Entity_genomic_entity_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT Relation_18__IDX PRIMARY KEY NONCLUSTERED (StructuralVariation_structural_variation_id, Genomic_Entity_genomic_entity_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Sequence_Data_File 
    (
     file_seq INTEGER NOT NULL , 
     file_name VARCHAR (120) NOT NULL , 
     file_format_type VARCHAR (20) , 
     analysis_id INTEGER NOT NULL , 
     biopsy_seq INTEGER NOT NULL , 
     patient_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT "Sequence_Data_File PK" PRIMARY KEY NONCLUSTERED (file_seq, analysis_id, biopsy_seq, patient_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE "StructVar-GenAnnot" 
    (
     StructuralVariation_structural_variation_id UNIQUEIDENTIFIER NOT NULL , 
     GenomicAnnotation_gap_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT Relation_22__IDX PRIMARY KEY NONCLUSTERED (StructuralVariation_structural_variation_id, GenomicAnnotation_gap_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE StructuralVariation 
    (
     structural_variation_id UNIQUEIDENTIFIER NOT NULL , 
     sv_description VARCHAR (256) , 
     bioportal_mutation_code VARCHAR (20) NOT NULL , 
     HGVS_id VARCHAR (30) NOT NULL , 
     sv_type_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT "StructuralVariation PK" PRIMARY KEY NONCLUSTERED (structural_variation_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE StructuralVariationCollection 
    (
     svc_seq INTEGER NOT NULL , 
     LOH_flag BIT , 
     CIRCOS_image IMAGE , 
     somatic_mut_flag BIT , 
     cancer_mut_flag BIT , 
     comments VARCHAR (2048) , 
     analysis_id INTEGER NOT NULL , 
     biopsy_seq INTEGER NOT NULL , 
     patient_id UNIQUEIDENTIFIER NOT NULL , 
     structural_variation_id UNIQUEIDENTIFIER NOT NULL , 
     CONSTRAINT "StructuralVariationCollection PK" PRIMARY KEY NONCLUSTERED (svc_seq, analysis_id, biopsy_seq, patient_id, structural_variation_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Structural_Variation_Type 
    (
     sv_type_id UNIQUEIDENTIFIER NOT NULL , 
     sv_description VARCHAR (256) , 
     sv_ontology_id VARCHAR (128) , 
     CONSTRAINT "Structural_Variation_Type PK" PRIMARY KEY NONCLUSTERED (sv_type_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE User_Account 
    (
     user_account_id UNIQUEIDENTIFIER NOT NULL , 
     user_full_name VARCHAR (80) NOT NULL , 
     user_email VARCHAR (80) NOT NULL , 
     user_affiliation VARCHAR (80) , 
     valid_account_flag BIT , 
     patient_data_access_level INTEGER , 
     annotation_flag BIT , 
     last_login DATETIME , 
     CONSTRAINT "User_Account PK" PRIMARY KEY NONCLUSTERED (user_account_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Web_Reference 
    (
     reference_id UNIQUEIDENTIFIER NOT NULL , 
     reference_site_page VARCHAR (120) NOT NULL , 
     resource_id VARCHAR (12) NOT NULL , 
     CONSTRAINT "Reference PK" PRIMARY KEY NONCLUSTERED (reference_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    



CREATE TABLE Web_Reference_Resource 
    (
     resource_id VARCHAR (12) NOT NULL , 
     resource_name VARCHAR (40) , 
     resource_base_url VARCHAR (80) , 
     resource_description VARCHAR (80) , 
     CONSTRAINT "Web_Reference_Resource PK" PRIMARY KEY NONCLUSTERED (resource_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    )
    ON "default"
GO 

    


ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Cancer_Classification FOREIGN KEY 
    ( 
     cancer_classification_id
    ) 
    REFERENCES Classification 
    ( 
     classification_id 
    ) 
GO 


ALTER TABLE Relation_18 
    ADD CONSTRAINT FK_ASS_11 FOREIGN KEY 
    ( 
     StructuralVariation_structural_variation_id
    ) 
    REFERENCES StructuralVariation 
    ( 
     structural_variation_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE Relation_18 
    ADD CONSTRAINT FK_ASS_12 FOREIGN KEY 
    ( 
     Genomic_Entity_genomic_entity_id
    ) 
    REFERENCES Genomic_Entity 
    ( 
     genomic_entity_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE "StructVar-GenAnnot" 
    ADD CONSTRAINT FK_ASS_15 FOREIGN KEY 
    ( 
     StructuralVariation_structural_variation_id
    ) 
    REFERENCES StructuralVariation 
    ( 
     structural_variation_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE "StructVar-GenAnnot" 
    ADD CONSTRAINT FK_ASS_16 FOREIGN KEY 
    ( 
     GenomicAnnotation_gap_id
    ) 
    REFERENCES GenomicAnnotation 
    ( 
     gap_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE "GenEntity-GenAnnot" 
    ADD CONSTRAINT FK_ASS_17 FOREIGN KEY 
    ( 
     Genomic_Entity_genomic_entity_id
    ) 
    REFERENCES Genomic_Entity 
    ( 
     genomic_entity_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE "GenEntity-GenAnnot" 
    ADD CONSTRAINT FK_ASS_18 FOREIGN KEY 
    ( 
     GenomicAnnotation_gap_id
    ) 
    REFERENCES GenomicAnnotation 
    ( 
     gap_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE Gene_GenAnnot 
    ADD CONSTRAINT FK_ASS_22 FOREIGN KEY 
    ( 
     GenomicAnnotation_gap_id
    ) 
    REFERENCES GenomicAnnotation 
    ( 
     gap_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Relation_10 FOREIGN KEY 
    ( 
     parent_biopsy_seq, 
     parent_patient_id
    ) 
    REFERENCES Patient_Biopsy 
    ( 
     biopsy_seq , 
     patient_id 
    ) 
GO 


ALTER TABLE GenomicAnalysis 
    ADD CONSTRAINT Relation_10 FOREIGN KEY 
    ( 
     classification_id
    ) 
    REFERENCES Classification 
    ( 
     classification_id 
    ) 
GO 


ALTER TABLE Clinical_Note_Audit 
    ADD CONSTRAINT Relation_11 FOREIGN KEY 
    ( 
     clinical_note_id, 
     patient_id
    ) 
    REFERENCES ClinicalNote 
    ( 
     clinical_note_id , 
     patient_id 
    ) 
GO 


ALTER TABLE Sequence_Data_File 
    ADD CONSTRAINT Relation_13 FOREIGN KEY 
    ( 
     analysis_id, 
     biopsy_seq, 
     patient_id
    ) 
    REFERENCES GenomicAnalysis 
    ( 
     analysis_id , 
     biopsy_seq , 
     patient_id1 
    ) 
GO 


ALTER TABLE StructuralVariationCollection 
    ADD CONSTRAINT Relation_15 FOREIGN KEY 
    ( 
     analysis_id, 
     biopsy_seq, 
     patient_id
    ) 
    REFERENCES GenomicAnalysis 
    ( 
     analysis_id , 
     biopsy_seq , 
     patient_id1 
    ) 
GO 


ALTER TABLE StructuralVariationCollection 
    ADD CONSTRAINT Relation_16 FOREIGN KEY 
    ( 
     structural_variation_id
    ) 
    REFERENCES StructuralVariation 
    ( 
     structural_variation_id 
    ) 
GO 


ALTER TABLE StructuralVariation 
    ADD CONSTRAINT Relation_17 FOREIGN KEY 
    ( 
     sv_type_id
    ) 
    REFERENCES Structural_Variation_Type 
    ( 
     sv_type_id 
    ) 
GO 


ALTER TABLE ClinicalNote 
    ADD CONSTRAINT Relation_20 FOREIGN KEY 
    ( 
     clinical_note_type_id
    ) 
    REFERENCES Clinical_Note_Type 
    ( 
     clinical_note_type_id 
    ) 
GO 


ALTER TABLE GenomicAnnotation 
    ADD CONSTRAINT Relation_21 FOREIGN KEY 
    ( 
     gat_id
    ) 
    REFERENCES GenomicAnnotationType 
    ( 
     gat_id 
    ) 
GO 


ALTER TABLE Genomic_Entity 
    ADD CONSTRAINT Relation_25 FOREIGN KEY 
    ( 
     get_id
    ) 
    REFERENCES Genomic_Entity_Type 
    ( 
     get_id 
    ) 
GO 


ALTER TABLE Web_Reference 
    ADD CONSTRAINT Relation_26 FOREIGN KEY 
    ( 
     resource_id
    ) 
    REFERENCES Web_Reference_Resource 
    ( 
     resource_id 
    ) 
GO 


ALTER TABLE GenomicAnnotation 
    ADD CONSTRAINT Relation_27 FOREIGN KEY 
    ( 
     reference_id
    ) 
    REFERENCES Web_Reference 
    ( 
     reference_id 
    ) 
GO 


ALTER TABLE Clinical_Note_Audit 
    ADD CONSTRAINT Relation_28 FOREIGN KEY 
    ( 
     user_account_id
    ) 
    REFERENCES User_Account 
    ( 
     user_account_id 
    ) 
GO 


ALTER TABLE Clinical_Note_Audit 
    ADD CONSTRAINT Relation_29 FOREIGN KEY 
    ( 
     patient_id1
    ) 
    REFERENCES Patient 
    ( 
     patient_id 
    ) 
GO 


ALTER TABLE ClinicalNote 
    ADD CONSTRAINT Relation_3 FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES Patient 
    ( 
     patient_id 
    ) 
GO 


ALTER TABLE GenomicAnnotation 
    ADD CONSTRAINT Relation_30 FOREIGN KEY 
    ( 
     user_account_id
    ) 
    REFERENCES User_Account 
    ( 
     user_account_id 
    ) 
GO 


ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Relation_5 FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES Patient 
    ( 
     patient_id 
    ) 
GO 


ALTER TABLE GenomicAnalysis 
    ADD CONSTRAINT Relation_8 FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES Patient 
    ( 
     patient_id 
    ) 
    ON DELETE CASCADE 
GO 


ALTER TABLE GenomicAnalysis 
    ADD CONSTRAINT Relation_9 FOREIGN KEY 
    ( 
     biopsy_seq, 
     patient_id1
    ) 
    REFERENCES Patient_Biopsy 
    ( 
     biopsy_seq , 
     patient_id 
    ) 
GO 


ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Site_Classification FOREIGN KEY 
    ( 
     site_classification_id
    ) 
    REFERENCES Classification 
    ( 
     classification_id 
    ) 
GO 

























-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            23
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
