-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2011-07-24 18:35:44 PDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE Classification 
    ( 
     primary_classification VARCHAR2 (128) , 
     subclass1 VARCHAR2 (128) , 
     subclass2 VARCHAR2 (128) , 
     subclass3 VARCHAR2 (128) , 
     comments VARCHAR2 (512) , 
     classification_id CHAR  NOT NULL , 
     subclass4 VARCHAR2 (128) 
    ) 
;



ALTER TABLE Classification 
    ADD CONSTRAINT Classification_PK PRIMARY KEY ( classification_id ) ;


CREATE TABLE ClinicalNote 
    ( 
     clinical_note_id CHAR  NOT NULL , 
     note VARCHAR2 (512)  NOT NULL , 
     patient_id CHAR  NOT NULL , 
     soft_delete_flag CHAR (1) , 
     clinical_note_type_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE ClinicalNote 
    ADD CONSTRAINT "ClinicalNote PK" PRIMARY KEY ( clinical_note_id, patient_id ) ;


CREATE TABLE Clinical_Note_Audit 
    ( 
     audit_date DATE  NOT NULL , 
     action_type VARCHAR2 (10)  NOT NULL , 
     access_seq INTEGER  NOT NULL , 
     user_account_id CHAR  NOT NULL , 
     patient_id1 CHAR  NOT NULL , 
     user_account VARCHAR2 (60)  NOT NULL , 
     clinical_note_id CHAR  NOT NULL , 
     patient_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE Clinical_Note_Audit 
    ADD CONSTRAINT PK_Clinical_Note_Audit PRIMARY KEY ( access_seq, patient_id1 ) ;


CREATE TABLE Clinical_Note_Type 
    ( 
     clinical_note_type_id CHAR  NOT NULL , 
     cn_type VARCHAR2 (60) 
    ) 
;



ALTER TABLE Clinical_Note_Type 
    ADD CONSTRAINT "Clinical_Note_Type PK" PRIMARY KEY ( clinical_note_type_id ) ;


CREATE TABLE "GenEntity-GenAnnot" 
    ( 
    
--  ERROR: Column name length exceeds maximum allowed length(30) 
 Genomic_Entity_genomic_entity_id CHAR  NOT NULL , 
     GenomicAnnotation_gap_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE "GenEntity-GenAnnot" 
    ADD CONSTRAINT Relation_23__IDX PRIMARY KEY ( Genomic_Entity_genomic_entity_id, GenomicAnnotation_gap_id ) ;


CREATE TABLE Gene 
    ( 
     gene_id CHAR , 
     HUGO_gene_symbol VARCHAR2 (6)  NOT NULL 
    ) 
;




CREATE TABLE Gene_GenAnnot 
    ( 
     GenomicAnnotation_gap_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE Gene_GenAnnot 
    ADD CONSTRAINT Relation_24__IDX PRIMARY KEY ( GenomicAnnotation_gap_id ) ;


CREATE TABLE GenomicAnalysis 
    ( 
     analysis_id INTEGER  NOT NULL , 
     analysis_date DATE  NOT NULL , 
     coverage INTEGER , 
     analysis_type VARCHAR2 (120) , 
     analysis_comments VARCHAR2 (1024) , 
     biopsy_seq INTEGER  NOT NULL , 
     patient_id1 CHAR  NOT NULL , 
     patient_id CHAR  NOT NULL , 
     classification_id CHAR 
    ) 
;



ALTER TABLE GenomicAnalysis 
    ADD CONSTRAINT "GenomicAnalysis PK" PRIMARY KEY ( analysis_id, biopsy_seq, patient_id1 ) ;


CREATE TABLE GenomicAnnotation 
    ( 
     gap_id CHAR  NOT NULL , 
     chromosome_loc VARCHAR2 (8)  NOT NULL , 
     chr_start_pos INTEGER , 
     chr_end_pos INTEGER , 
     cds_start_pos INTEGER , 
     cds_end_pos INTEGER , 
     UCSC_coordinates VARCHAR2 (30) , 
     gat_id CHAR  NOT NULL , 
     annotation VARCHAR2 (2048) , 
     soft_delete_flag CHAR (1) , 
     annotation_date DATE  NOT NULL , 
     bioportal_evidence_code VARCHAR2 (12) , 
     reference_id CHAR , 
     user_account_id CHAR  NOT NULL , 
     user_account VARCHAR2 (60)  NOT NULL 
    ) 
;



ALTER TABLE GenomicAnnotation 
    ADD CONSTRAINT "GenomicFeature PK" PRIMARY KEY ( gap_id ) ;


CREATE TABLE GenomicAnnotationType 
    ( 
     gat_id CHAR  NOT NULL , 
     ga_type VARCHAR2 (128)  NOT NULL 
    ) 
;



ALTER TABLE GenomicAnnotationType 
    ADD CONSTRAINT "GenomicAnnotationType PK" PRIMARY KEY ( gat_id ) ;


CREATE TABLE Genomic_Entity 
    ( 
     genomic_entity_id CHAR  NOT NULL , 
     ge_description VARCHAR2 (128) , 
     get_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE Genomic_Entity 
    ADD CONSTRAINT "Genomic_Entity PK" PRIMARY KEY ( genomic_entity_id ) ;


CREATE TABLE Genomic_Entity_Type 
    ( 
     get_id CHAR  NOT NULL , 
     ge_type VARCHAR2 (80)  NOT NULL 
    ) 
;



ALTER TABLE Genomic_Entity_Type 
    ADD CONSTRAINT "Genomic_Entity_Type PK" PRIMARY KEY ( get_id ) ;


CREATE TABLE Patient 
    ( 
     patient_id CHAR  NOT NULL , 
     sex VARCHAR2 (6) , 
     date_of_birth DATE , 
     date_of_death DATE , 
     family_history_flag CHAR (1) , 
     soft_delete_flag CHAR (1) 
    ) 
;



ALTER TABLE Patient 
    ADD CONSTRAINT "Patient PK" PRIMARY KEY ( patient_id ) ;


CREATE TABLE Patient_Biopsy 
    ( 
     biopsy_seq INTEGER  NOT NULL , 
     biopsy_date DATE , 
     diagnosis VARCHAR2 (60) , 
     histological_image BLOB , 
     patient_id CHAR  NOT NULL , 
     site_classification_id CHAR  NOT NULL , 
     cancer_classification_id CHAR , 
     parent_biopsy_seq INTEGER , 
     parent_patient_id CHAR , 
     soft_delete_flag CHAR (1) 
    ) 
;



ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Biopsy_PK PRIMARY KEY ( biopsy_seq, patient_id ) ;


CREATE TABLE Relation_18 
    ( 
    
--  ERROR: Column name length exceeds maximum allowed length(30) 
 StructuralVariation_structural_variation_id CHAR  NOT NULL , 
    
--  ERROR: Column name length exceeds maximum allowed length(30) 
 Genomic_Entity_genomic_entity_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE Relation_18 
    ADD CONSTRAINT Relation_18__IDX PRIMARY KEY ( StructuralVariation_structural_variation_id, Genomic_Entity_genomic_entity_id ) ;


CREATE TABLE Sequence_Data_File 
    ( 
     file_seq INTEGER  NOT NULL , 
     file_name VARCHAR2 (120)  NOT NULL , 
     file_format_type VARCHAR2 (20) , 
     analysis_id INTEGER  NOT NULL , 
     biopsy_seq INTEGER  NOT NULL , 
     patient_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE Sequence_Data_File 
    ADD CONSTRAINT "Sequence_Data_File PK" PRIMARY KEY ( file_seq, analysis_id, biopsy_seq, patient_id ) ;


CREATE TABLE "StructVar-GenAnnot" 
    ( 
    
--  ERROR: Column name length exceeds maximum allowed length(30) 
 StructuralVariation_structural_variation_id CHAR  NOT NULL , 
     GenomicAnnotation_gap_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE "StructVar-GenAnnot" 
    ADD CONSTRAINT Relation_22__IDX PRIMARY KEY ( StructuralVariation_structural_variation_id, GenomicAnnotation_gap_id ) ;


CREATE TABLE StructuralVariation 
    ( 
     structural_variation_id CHAR  NOT NULL , 
     sv_description VARCHAR2 (256) , 
     bioportal_mutation_code VARCHAR2 (20)  NOT NULL , 
     HGVS_id VARCHAR2 (30)  NOT NULL , 
     sv_type_id CHAR  NOT NULL 
    ) 
;



ALTER TABLE StructuralVariation 
    ADD CONSTRAINT "StructuralVariation PK" PRIMARY KEY ( structural_variation_id ) ;


CREATE TABLE StructuralVariationCollection 
    ( 
     svc_seq INTEGER  NOT NULL , 
     LOH_flag CHAR (1) , 
     CIRCOS_image BLOB , 
     somatic_mut_flag CHAR (1) , 
     cancer_mut_flag CHAR (1) , 
     comments VARCHAR2 (2048) , 
     analysis_id INTEGER  NOT NULL , 
     biopsy_seq INTEGER  NOT NULL , 
     patient_id CHAR  NOT NULL , 
     structural_variation_id CHAR  NOT NULL 
    ) 
;




--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE StructuralVariationCollection 
    ADD CONSTRAINT "StructuralVariationCollection PK" PRIMARY KEY ( svc_seq, analysis_id, biopsy_seq, patient_id, structural_variation_id ) ;


CREATE TABLE Structural_Variation_Type 
    ( 
     sv_type_id CHAR  NOT NULL , 
     sv_description VARCHAR2 (256) , 
     sv_ontology_id VARCHAR2 (128) 
    ) 
;



ALTER TABLE Structural_Variation_Type 
    ADD CONSTRAINT "Structural_Variation_Type PK" PRIMARY KEY ( sv_type_id ) ;


CREATE TABLE User_Account 
    ( 
     user_account_id CHAR  NOT NULL , 
     user_full_name VARCHAR2 (80)  NOT NULL , 
     user_email VARCHAR2 (80)  NOT NULL , 
     user_affiliation VARCHAR2 (80) , 
     valid_account_flag CHAR (1) , 
     patient_data_access_level INTEGER , 
     annotation_flag CHAR (1) , 
     last_login DATE 
    ) 
;



ALTER TABLE User_Account 
    ADD CONSTRAINT "User_Account PK" PRIMARY KEY ( user_account_id ) ;


CREATE TABLE Web_Reference 
    ( 
     reference_id CHAR  NOT NULL , 
     reference_site_page VARCHAR2 (120)  NOT NULL , 
     resource_id VARCHAR2 (12)  NOT NULL 
    ) 
;



ALTER TABLE Web_Reference 
    ADD CONSTRAINT "Reference PK" PRIMARY KEY ( reference_id ) ;


CREATE TABLE Web_Reference_Resource 
    ( 
     resource_id VARCHAR2 (12)  NOT NULL , 
     resource_name VARCHAR2 (40) , 
     resource_base_url VARCHAR2 (80) , 
     resource_description VARCHAR2 (80) 
    ) 
;



ALTER TABLE Web_Reference_Resource 
    ADD CONSTRAINT "Web_Reference_Resource PK" PRIMARY KEY ( resource_id ) ;



ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Cancer_Classification FOREIGN KEY 
    ( 
     cancer_classification_id
    ) 
    REFERENCES Classification 
    ( 
     classification_id
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE Relation_18 
    ADD CONSTRAINT FK_ASS_11 FOREIGN KEY 
    ( 
     StructuralVariation_structural_variation_id
    ) 
    REFERENCES StructuralVariation 
    ( 
     structural_variation_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE Relation_18 
    ADD CONSTRAINT FK_ASS_12 FOREIGN KEY 
    ( 
     Genomic_Entity_genomic_entity_id
    ) 
    REFERENCES Genomic_Entity 
    ( 
     genomic_entity_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE "StructVar-GenAnnot" 
    ADD CONSTRAINT FK_ASS_15 FOREIGN KEY 
    ( 
     StructuralVariation_structural_variation_id
    ) 
    REFERENCES StructuralVariation 
    ( 
     structural_variation_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE "StructVar-GenAnnot" 
    ADD CONSTRAINT FK_ASS_16 FOREIGN KEY 
    ( 
     GenomicAnnotation_gap_id
    ) 
    REFERENCES GenomicAnnotation 
    ( 
     gap_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE "GenEntity-GenAnnot" 
    ADD CONSTRAINT FK_ASS_17 FOREIGN KEY 
    ( 
     Genomic_Entity_genomic_entity_id
    ) 
    REFERENCES Genomic_Entity 
    ( 
     genomic_entity_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE "GenEntity-GenAnnot" 
    ADD CONSTRAINT FK_ASS_18 FOREIGN KEY 
    ( 
     GenomicAnnotation_gap_id
    ) 
    REFERENCES GenomicAnnotation 
    ( 
     gap_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE Gene_GenAnnot 
    ADD CONSTRAINT FK_ASS_22 FOREIGN KEY 
    ( 
     GenomicAnnotation_gap_id
    ) 
    REFERENCES GenomicAnnotation 
    ( 
     gap_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Relation_10 FOREIGN KEY 
    ( 
     parent_biopsy_seq,
     parent_patient_id
    ) 
    REFERENCES Patient_Biopsy 
    ( 
     biopsy_seq,
     patient_id
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE GenomicAnalysis 
    ADD CONSTRAINT Relation_10 FOREIGN KEY 
    ( 
     classification_id
    ) 
    REFERENCES Classification 
    ( 
     classification_id
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE Clinical_Note_Audit 
    ADD CONSTRAINT Relation_11 FOREIGN KEY 
    ( 
     clinical_note_id,
     patient_id
    ) 
    REFERENCES ClinicalNote 
    ( 
     clinical_note_id,
     patient_id
    ) 
;


ALTER TABLE Sequence_Data_File 
    ADD CONSTRAINT Relation_13 FOREIGN KEY 
    ( 
     analysis_id,
     biopsy_seq,
     patient_id
    ) 
    REFERENCES GenomicAnalysis 
    ( 
     analysis_id,
     biopsy_seq,
     patient_id1
    ) 
;


ALTER TABLE StructuralVariationCollection 
    ADD CONSTRAINT Relation_15 FOREIGN KEY 
    ( 
     analysis_id,
     biopsy_seq,
     patient_id
    ) 
    REFERENCES GenomicAnalysis 
    ( 
     analysis_id,
     biopsy_seq,
     patient_id1
    ) 
;


ALTER TABLE StructuralVariationCollection 
    ADD CONSTRAINT Relation_16 FOREIGN KEY 
    ( 
     structural_variation_id
    ) 
    REFERENCES StructuralVariation 
    ( 
     structural_variation_id
    ) 
;


ALTER TABLE StructuralVariation 
    ADD CONSTRAINT Relation_17 FOREIGN KEY 
    ( 
     sv_type_id
    ) 
    REFERENCES Structural_Variation_Type 
    ( 
     sv_type_id
    ) 
;


ALTER TABLE ClinicalNote 
    ADD CONSTRAINT Relation_20 FOREIGN KEY 
    ( 
     clinical_note_type_id
    ) 
    REFERENCES Clinical_Note_Type 
    ( 
     clinical_note_type_id
    ) 
;


ALTER TABLE GenomicAnnotation 
    ADD CONSTRAINT Relation_21 FOREIGN KEY 
    ( 
     gat_id
    ) 
    REFERENCES GenomicAnnotationType 
    ( 
     gat_id
    ) 
;


ALTER TABLE Genomic_Entity 
    ADD CONSTRAINT Relation_25 FOREIGN KEY 
    ( 
     get_id
    ) 
    REFERENCES Genomic_Entity_Type 
    ( 
     get_id
    ) 
;


ALTER TABLE Web_Reference 
    ADD CONSTRAINT Relation_26 FOREIGN KEY 
    ( 
     resource_id
    ) 
    REFERENCES Web_Reference_Resource 
    ( 
     resource_id
    ) 
;


ALTER TABLE GenomicAnnotation 
    ADD CONSTRAINT Relation_27 FOREIGN KEY 
    ( 
     reference_id
    ) 
    REFERENCES Web_Reference 
    ( 
     reference_id
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE Clinical_Note_Audit 
    ADD CONSTRAINT Relation_28 FOREIGN KEY 
    ( 
     user_account_id
    ) 
    REFERENCES User_Account 
    ( 
     user_account_id
    ) 
;


ALTER TABLE Clinical_Note_Audit 
    ADD CONSTRAINT Relation_29 FOREIGN KEY 
    ( 
     patient_id1
    ) 
    REFERENCES Patient 
    ( 
     patient_id
    ) 
;


ALTER TABLE ClinicalNote 
    ADD CONSTRAINT Relation_3 FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES Patient 
    ( 
     patient_id
    ) 
;


ALTER TABLE GenomicAnnotation 
    ADD CONSTRAINT Relation_30 FOREIGN KEY 
    ( 
     user_account_id
    ) 
    REFERENCES User_Account 
    ( 
     user_account_id
    ) 
;


ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Relation_5 FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES Patient 
    ( 
     patient_id
    ) 
;


ALTER TABLE GenomicAnalysis 
    ADD CONSTRAINT Relation_8 FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES Patient 
    ( 
     patient_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE GenomicAnalysis 
    ADD CONSTRAINT Relation_9 FOREIGN KEY 
    ( 
     biopsy_seq,
     patient_id1
    ) 
    REFERENCES Patient_Biopsy 
    ( 
     biopsy_seq,
     patient_id
    ) 
;


ALTER TABLE Patient_Biopsy 
    ADD CONSTRAINT Site_Classification FOREIGN KEY 
    ( 
     site_classification_id
    ) 
    REFERENCES Classification 
    ( 
     classification_id
    ) 
;


























-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            23
-- CREATE INDEX                             0
-- ALTER TABLE                             50
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   5
-- WARNINGS                                 0
